### PR TITLE
Curaçao added

### PR DESCRIPTION
**Pull request by dennisoderwald**
I noticed that the country "Curaçao" was not included.

### CODE REVIEW

**Comment by dannyvankooten** [comment]
Heh, that's weird. I must have copied an incomplete ISO-3166 list initially. That probably means more countries are missing. Thanks for noticing it!

**Comment by dennisoderwald** [comment]
@dannyvankooten When do you plan to include it in a release? We would be reluctant to incorporate a dev booth.

**Comment by dennisoderwald** [comment]
@dannyvankooten ?

**Comment by dannyvankooten** [comment]
@dennisoderwald Done! Sorry for the delay. Got stuck trying to include another geolocation API service in the release, but should have just released right away.

**Pull request merged**
